[package]
name = "catalejo-sys"
version.workspace = true
edition.workspace = true
description = "System-level userspace bindings to the Mirilla kernel module."
repository.workspace = true
license.workspace = true
build = "build.rs"
exclude = ["c/include/mirilla/mirilla-symbol.generated.h"]

[features]
default = ["default-device-path"]
default-device-path = []
stealth-mode = []

[dependencies]
catalejo-memory.workspace = true
fack.workspace = true
libc.workspace = true
tokel.workspace = true

[build-dependencies]
bindgen.workspace = true
cc.workspace = true
walkdir.workspace = true
