[package]
name = "catalejo-fault"
version.workspace = true
edition.workspace = true
description = "Fault-tolerant memory access primitives for Catalejo."
repository.workspace = true
license.workspace = true

[lib]

[features]
stealth-mode = ["catalejo-sys/stealth-mode"]

[dependencies]
catalejo-memory.workspace = true
catalejo-sys.workspace = true
tokel.workspace = true

[dev-dependencies]
libc.workspace = true
