[package]
name = "catalejo-macro"
version.workspace = true
edition.workspace = true
description = "Derive macros for the Catalejo process-memory observation library."
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
